### PR TITLE
action: handle slashes in ref names

### LINKED ISSUE #62: _download_ref_asset does not handle file separators in branch names
**Description**

Hi, I'm currently experimenting with sigstore releases on a branch named `ci/release-workflow` in one of my repos. I got the following error on my first test run:

```
Traceback (most recent call last):
  File "/home/runner/work/_actions/sigstore/gh-action-sigstore-python/v1.2.3/action.py", line 189, in <module>
    artifact = _download_ref_asset(filetype)
  File "/home/runner/work/_actions/sigstore/gh-action-sigstore-python/v1.2.3/action.py", line 70, in _download_ref_asset
    with artifact.open("wb") as io:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ci/release-workflow.zip'
```

Looking at the code, this line seems to be the culprit: https://github.com/sigstore/gh-action-sigstore-python/blob/e323e1b02e26cc6600843935562c862b94200b0c/action.py#L65

`GITHUB_REF_NAME` is `ci/release-workflow` in my case, so the path is rendered as `/tmp/ci/release-workflow.zip`, which results in a file not found error because the `/tmp/ci` directory doesn't exist.

Suggest either of the following:

 - Sanitise the refname to remove/replace characters that can't appear in file names
 - Create all parent directories prior to writing the file

**Version**

`v1.2.3` of this GitHub action :)

### PR DESCRIPTION
**Pull request by woodruffw**
Fixes #62.

cc @MatthiasValvekens

### CODE REVIEW

**Comment by woodruffw** [comment]
Hmm, not sure why TUF is failing here:

```
Run /home/runner/work/gh-action-sigstore-python/gh-action-sigstore-python/.//action.py "./test/artifact.txt"
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/__main__.py", line 22, in <module>
    main()
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_cli.py", line 542, in main
    _sign(args)
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_cli.py", line 636, in _sign
    signer = Signer.staging()
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/sign.py", line 113, in staging
    rekor = RekorClient.staging(updater)
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_internal/rekor/client.py", line 296, in staging
    rekor_keys = updater.get_rekor_keys()
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_internal/tuf.py", line 178, in get_rekor_keys
    keys = self._get("Rekor", ["Active"])
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_internal/tuf.py", line 143, in _get
    self._updater = self._setup()
  File "/home/runner/.local/lib/python3.10/site-packages/sigstore/_internal/tuf.py", line 137, in _setup
    updater.refresh()
  File "/home/runner/.local/lib/python3.10/site-packages/tuf/ngclient/updater.py", line [132](https://github.com/sigstore/gh-action-sigstore-python/actions/runs/4774812030/jobs/8488732941#step:3:135), in refresh
    self._load_root()
  File "/home/runner/.local/lib/python3.10/site-packages/tuf/ngclient/updater.py", line 323, in _load_root
    self._trusted_set.update_root(data)
  File "/home/runner/.local/lib/python3.10/site-packages/tuf/ngclient/_internal/trusted_metadata_set.py", line 164, in update_root
    self.root.verify_delegate(Root.type, new_root)
  File "/home/runner/.local/lib/python3.10/site-packages/tuf/api/metadata.py", line 452, in verify_delegate
    raise exceptions.UnsignedMetadataError(
tuf.api.exceptions.UnsignedMetadataError: root was signed by 0/1 keys
```

I tried an equivalent `sigstore sign` locally, which succeeds. Will keep debugging.

CC @jku for potential opinions 🙂

**Comment by woodruffw** [comment]
This looks like it might be more fallout from the underlying cause of https://github.com/sigstore/sigstore-python/pull/594; CC @tnytown

**Comment by woodruffw** [comment]
The release in https://github.com/sigstore/sigstore-python/pull/621 should fix this.

**Review by tetsuo-cpp — APPROVED** [review]
LGTM!

**Pull request merged**
