### PR TITLE
action: implement and document `bundle-only`

### LINKED ISSUE #47: Add a setting to disable `.crt` and `.sig` outputs
From #46: these outputs are now redundant against `.sigstore`, but are included by default for backwards compatibility.

As such, we should add a setting (maybe `bundle-only: bool` or similar?) that allows a user to disable them if they don't need them and don't want them cluttering up their releases.

### PR DESCRIPTION
**Pull request by tnytown**
#### Summary

This changeset resolves #47 by adding the `bundle-only` setting, which disables the upload of `.crt` and `.sig` outputs.

#### Release Note

Implemented the `bundle-only` setting, which disables upload of `.crt` and `.sig` artifacts when used in conjunction
with `upload-signing-artifacts` and `release-signing-artifacts`.

#### Documentation

Documented in the README!

### CODE REVIEW

**Review by woodruffw — DISMISSED** [review]
LGTM; let's go ahead and configure it in the `release.yml` workflow as well!

**Comment by tnytown** [comment]
The respective outputs will be uploaded when `certificate` or `signature` are specified along with this setting, but I don't see why someone would do that? I can add a check for that if we feel that it is necessary

**Comment by woodruffw** [comment]
> The respective outputs will be uploaded when `certificate` or `signature` are specified along with this setting, but I don't see why someone would do that? I can add a check for that if we feel that it is necessary

Yeah, I was thinking about that -- IMO it's fine as is, since passing `certificate` and `signature` explicitly imply that they want specific filenames for those outputs, and that doesn't make much sense unless they explicitly end up as artifacts/assets.

That being said I think we can safely drop those two settings entirely with the next major release -- they stick out a bit and add unnecessary complexity to the action.

**Review by woodruffw — APPROVED** [review]

**Comment by woodruffw** [comment]
LGTM! I'll do a prerelease with this.

**Pull request merged**
